cabal-version:      1.24
name:               hash-string
version:            0.1.0.0
synopsis:           bytestring newtypes supporting constant-time base16, base64, and comparisons.
-- description:
license:            Apache-2.0
license-file:       LICENSE
author:             Steve "Sc00bz" Thomas, Leon P Smith
-- maintainer:
-- copyright:
category:           Cryptography
build-type:         Simple
extra-doc-files:    CHANGELOG.md

library
    exposed-modules:  Crypto.HashString
                      Crypto.HashString.FFI

    build-depends:    base,
                      bytestring,
                      ghc-prim
    hs-source-dirs:   lib
    include-dirs:     csrc

    install-includes:  csrc/hs_hashstring_memcmp.h
                       csrc/hs_hashstring_base16.h
                       csrc/hs_hashstring_base64.h
    c-sources:         csrc/hs_hashstring_memcmp.c
                       csrc/hs_hashstring_base16.c
                       csrc/hs_hashstring_base64.c

    default-language: Haskell2010

test-suite hash-string-test
    -- Base language which the package is written in.
    default-language: Haskell2010

    -- Modules included in this executable, other than Main.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:

    -- The interface type and version of the test suite.
    type:             exitcode-stdio-1.0

    -- Directories containing source files.
    hs-source-dirs:   test

    -- The entrypoint to the test suite.
    main-is:          Main.hs

    -- Test dependencies.
    build-depends:    base
                    , base16 >= 1
    --                , base64 >= 1
                    , bytestring
                    , hash-string
                    , quickcheck-instances
                    , tasty
                    , tasty-quickcheck
		    , text
